name: FantasyFreedomMod
main: me.fantasyfreedom.fantasyfreedommod.FantasyFreedomMod
version: ${tfm.build.version}
description: Plugin for the Fantasy Freedom server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza]

# plugin.yml is no longer used to define commands.
